edition_number: '1.3'
edition_handle: acme-v1.3
edition_pub_date: 2014-05
build_dir: build
articles:
- username: mojavelinux
  local_dir: acme-v1.3-mojavelinux
  repository:
    clone_url: https://github.com/acme-magazine-01/acme-v1.3-mojavelinux.git
    ssh_url: git@github.com:acme-magazine-01/acme-v1.3-mojavelinux.git
